Verify Hashicorp GPG signatures and checksums
This plugin did not check GPG signatures or checksums. So when the
CodeCov breach affected Hashicorp, leading to

https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512

and a GPG key update announcement on

https://www.hashicorp.com/security

the first thing I checked was whether my asdf plugin for Hashicorp Vault
had been updated to support the new key.

Alas, it hadn't! In fact, asdf wasn't verifying GPG signatures at all,
meaning that supply chain compromises of Hashicorp infrastructure could
trivially deliver compromised Vault, Terraform, and Consul binaries to
users.

To fix this, I've added signature and checksum verification to
asdf-hashicorp. The GPG key is static, included in this repo, because in
modeling a future attack where the adversary has control of HashiCorp's
webservers (but not their GPG notary server), we would remain at risk if
we simply fetched the latest key each time. Instead, maintainers of this
repository will need to update the GPG key in this repo when it expires
or is revoked because of a security incident.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -23,6 +23,40 @@ TMP_DOWNLOAD_DIR="$(mktemp -d -t "asdf_${toolname}_XXXXXX")"
 readonly TMP_DOWNLOAD_DIR
 trap 'rm -rf "${TMP_DOWNLOAD_DIR?}"' EXIT
 
+gnupg() {
+  GNUPGHOME="${TMP_DOWNLOAD_DIR}" gpg $@
+}
+
+verify() {
+  # Release archive checksum verification - see
+  # https://www.hashicorp.com/security
+  #
+  # Returns 1 on GPG signature verification error, 2 on checksum error.
+  local -r version="$1"
+  local -r zip_path="$2"
+  local -r platform="$(get_platform)"
+  local -r arch="$(get_arch)"
+  local -r gpg_path="${TMP_DOWNLOAD_DIR}/$(get_gpg_filename "${version}")"
+  local -r checksum_path="${TMP_DOWNLOAD_DIR}/$(get_checksum_filename "${version}")"
+
+  gnupg --import "${__dirname}/../hashicorp.asc"
+  if ! curl -fs "$(get_download_url "${version}" "checksum" )" -o "${checksum_path}"; then
+    echo "couldn't download checksum file" >&2
+  fi
+  if ! curl -fs "$(get_download_url "${version}" "gpg" )" -o "${gpg_path}"; then
+    echo "couldn't download gpg signature file" >&2
+  fi
+
+  if ! gnupg --verify "${gpg_path}" "${checksum_path}"; then
+    echo "gpg verification failed" >&2
+    return 1
+  fi
+  if ! (cd "${TMP_DOWNLOAD_DIR}" && shasum -a 256 -c <(grep "${platform}_${arch}.zip" "${checksum_path}") ); then
+    echo "checksum verification failed" >&2
+    return 2
+  fi
+}
+
 install() {
   local -r install_type="$1"
   local -r version="$2"
@@ -33,11 +67,14 @@ install() {
   fi
 
   local -r bin_install_path="${install_path}/bin"
-  local -r download_url="$(get_download_url "${version}")"
-  local -r download_path="${TMP_DOWNLOAD_DIR}/$(get_filename "${version}")"
+  local -r download_url="$(get_download_url "${version}" "zip")"
+  local -r download_path="${TMP_DOWNLOAD_DIR}/$(get_zip_filename "${version}")"
 
   echo "Downloading ${toolname} version ${version} from ${download_url}"
   if curl -fs "${download_url}" -o "${download_path}"; then
+    echo "Verifying signatures and checksums"
+    verify "${version}" "${download_path}"
+
     echo "Cleaning ${toolname} previous binaries"
     rm -rf "${bin_install_path:?}/${toolname}"
 
@@ -73,16 +110,42 @@ get_arch() {
   fi
 }
 
-get_filename() {
+get_zip_filename() {
   local -r version="$1"
   local -r platform="$(get_platform)"
   local -r arch="$(get_arch)"
   echo "${toolname}_${version}_${platform}_${arch}.zip"
 }
 
+get_checksum_filename() {
+  local -r version="$1"
+  echo "${toolname}_${version}_SHA256SUMS"
+}
+
+get_gpg_filename() {
+  local -r version="$1"
+  echo "${toolname}_${version}_SHA256SUMS.sig"
+}
+
 get_download_url() {
   local -r version="$1"
-  local -r filename="$(get_filename "${version}")"
+  local -r type="$2"
+
+  case "${type}" in
+    zip)
+      local -r filename="$(get_zip_filename "${version}")"
+    ;;
+    checksum)
+      local -r filename="$(get_checksum_filename "${version}")"
+    ;;
+    gpg)
+      local -r filename="$(get_gpg_filename "${version}")"
+    ;;
+    *)
+      echo "${type} is not a valid type of URL to download" >&2
+      exit 1
+    ;;
+  esac
   local -r releases_host="https://releases.hashicorp.com"
 
   if ! curl -fs "${releases_host}/${toolname}/${version}/${filename}" >/dev/null && [[ ${filename} == *"arm64"* ]]; then
